購入履歴画面、購入明細画面を作成しました
kakeisbs/lamp_practice pull request #15
Opened 2020-04-23 11:51 UTC by kakeisbs

購入履歴画面、購入明細画面を作成しました。マージ宜しくお願い致します。

2020-04-25 20:43 UTC, thisprodigiousgeek requested changes
かなり完成に近づいてきましたね！指摘箇所を修正して最後の仕上げをしていきましょう！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +$check_csrf_token = get_get('token');
POSTで値が送信されているわけではないので、トークンは不要ですね！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +}
他人の注文の注文明細を表示しようとするとどうなるか確認してみましょう！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +    $sums = order_sum($db, $order_id);
order_sum関数を利用しなくても、get_orderで合計金額は計算できそうですね！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/model/order_detail.php
> +function get_order_detail($db, $order_id, $user_id) {
複数のorder_detailを取得するので関数名は複数形が望ましいですね！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/view/order_detail_view.php
> +                        <td><?php print h($order_detail['amount']);?></td>
数量も4桁以上になる可能性はありますね！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/view/order_view.php
> +                            <td><?php print h(number_format($order['SUM(order_details.price * order_details.amount)'])); ?>円</td>
asを使えば、この長いキーを改善できそうですね！

2020-04-25 20:43 UTC, thisprodigiousgeek commented on www/view/order_view.php
> +                                <form action="order_detail.php" method="get">
order_detail.phpへのパスも定数化できますね！

2020-04-27 06:32 UTC, kakeisbs commented
ご指摘ありがとうございます。修正箇所を再度訂正しました。確認後、マージのほどよろしくお願い致します。

2020-04-28 08:48 UTC, thisprodigiousgeek requested changes
完成間近ですね！ユーザーが一致しているかどうかのチェックを効率化できれば完成です！
ラストスパート、身体に無理のない範囲で頑張っていきましょう！

2020-04-28 08:48 UTC, thisprodigiousgeek commented on www/html/order_detail.php
> +    if(get_order($db, $order_id) === false) {
get_orderが複数回実行されていますね！一回で済ます方法を考えましょう。

2020-04-28 09:38 UTC, kakeisbs commented
再度、訂正箇所を修正しました。こちらでよろしければマージお願い致します。

2020-04-28 12:18 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2020-04-28 12:19 UTC, merged