課題3の並び替え機能を実装しました
kakeisbs/lamp_practice pull request #17
Opened 2020-04-30 05:04 UTC by kakeisbs

並び替え機能を実装しました。ご確認かつマージの方宜しくお願い致します。

2020-04-30 09:28 UTC, thisprodigiousgeek requested changes
まずは並べ替えの仕組みを実装していただけましたね！素晴らしいです。ここからは、getで渡された値に応じて行う処理の分岐を効率的にしていきましょう！

2020-04-30 09:28 UTC, thisprodigiousgeek commented on www/html/index.php
> +  $items = items_sort($db, $sort);
$itemsを2回取得しているのは非効率ですね！$sortの値に応じて、get_open_itemsでソートができるようにしてみましょう！

2020-04-30 09:28 UTC, thisprodigiousgeek commented on www/model/item.php
> +      CASE ?
SQLのcase文を利用するのは非効率ですね！PHP側でif文で分岐させましょう。

2020-05-02 10:05 UTC, thisprodigiousgeek requested changes
ほぼ完成していらっしゃいますね！不要な関数の削除と、選択したプルダウンの保持の実装を行い仕上げておきましょう！

2020-05-02 10:05 UTC, thisprodigiousgeek commented on www/model/item.php
> +function items_sort($db, $sort) {
利用していないitems_sortが残っているので削除しておきましょう！

2020-05-02 10:05 UTC, thisprodigiousgeek commented on www/view/index_view.php
> +            <option value="created_DESC">新着順</option>
選択されたoptionが並べ替え後にそのまま選択された状態にしておくにはどうすれば良いでしょうか？

2020-05-02 11:37 UTC, kakeisbs commented
ご指摘ありがとうございます。修正行いました。ご確認よろしくお願い致します。

2020-05-02 11:55 UTC, thisprodigiousgeek requested changes
ほぼ出来上がりです！コメントを参考に修正しましょう！

2020-05-02 11:55 UTC, thisprodigiousgeek commented on www/view/index_view.php
> +            <option value="created_DESC" <?= $sort == 'created_DESC' ? 'selected' : "" ?>>新着順</option>
惜しいですね！比較は必ず厳密なものを利用し、クォーテーションはシングルを利用しましょう！

2020-05-02 11:55 UTC, thisprodigiousgeek commented on www/view/index_view.php
> +            <option value="created_DESC" <?= $sort == 'created_DESC' ? 'selected' : "" ?>>新着順</option>
また、後ろ二つは手前のダブルクォートとくっついているので気をつけましょう。

2020-05-03 01:44 UTC, kakeisbs commented
修正し、コミットしております。ご確認宜しくお願い致します。

2020-05-03 07:28 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2020-05-03 07:29 UTC, merged